blank_issues_enabled: false
contact_links:
  - name: Submit an idea for a stream
    url: https://github.com/elementary/streams/discussions/categories/ideas
    about: We're using GitHub Discussions to accept and manage stream ideas
  - name: Report an issue with elementary OS from elementary OS
    url: settings://about
    about: If you're on elementary OS, report an issue from System Settings → About → Report a Problem
  - name: Report an issue with elementary OS on GitHub
    url: https://github.com/elementary
    about: Please find the appropriate repository and file an issue there
